2022-02-06 03:34:02.679668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/software/software/Python/3.7.4-GCCcore-8.3.0/lib:/opt/software/software/libffi/3.2.1-GCCcore-8.3.0/lib64:/opt/software/software/libffi/3.2.1-GCCcore-8.3.0/lib:/opt/software/software/GMP/6.1.2-GCCcore-8.3.0/lib:/opt/software/software/XZ/5.2.4-GCCcore-8.3.0/lib:/opt/software/software/SQLite/3.29.0-GCCcore-8.3.0/lib:/opt/software/software/Tcl/8.6.9-GCCcore-8.3.0/lib:/opt/software/software/libreadline/8.0-GCCcore-8.3.0/lib:/opt/software/software/ncurses/6.1-GCCcore-8.3.0/lib:/opt/software/software/bzip2/1.0.8-GCCcore-8.3.0/lib:/opt/software/software/binutils/2.32-GCCcore-8.3.0/lib:/opt/software/software/zlib/1.2.11-GCCcore-8.3.0/lib:/opt/software/software/GCCcore/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0:/opt/software/software/GCCcore/8.3.0/lib64:/opt/software/software/GCCcore/8.3.0/lib
2022-02-06 03:34:02.683708: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/homes/okerinde/projects/anomaly_detection_sport_video/codes/detecting_risky_tackles_in_sport_videos_using_transformer_beocat.py", line 37, in <module>
    from tensorflow.keras import layers
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/api/_v2/keras/__init__.py", line 10, in <module>
    from keras import __version__
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/metrics.py", line 27, in <module>
    from keras import activations
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/layers/__init__.py", line 24, in <module>
    from keras.engine.input_layer import Input
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/engine/base_layer.py", line 41, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/homes/okerinde/virtualenvs/anomaly_sport_video/lib/python3.7/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 1180, in <module>
    mixed_precision._register_wrapper_optimizer_cls(optimizer_v2.OptimizerV2,
AttributeError: module 'tensorflow.python.training.experimental.mixed_precision' has no attribute '_register_wrapper_optimizer_cls'
